name=AS3935LightningSensor
version=0.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=Library for the ScioSense AS3935 Lightning Sensor
paragraph=
category=Sensors
includes=AS3935LightningSensor.h
url=https://github.com/mumanchu/AS3935LightningSensor
architectures=*

